# Generated by Django 4.1.3 on 2022-12-25 12:40

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(validators=[core.validators.check_age], verbose_name='Возраст')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'Основатель',
                'verbose_name_plural': 'Основатели',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('location', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('auto', models.CharField(max_length=255, verbose_name='Авто')),
                ('reviews', models.TextField(max_length=500, verbose_name='Отзывы')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.founder')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ('name',),
            },
        ),
    ]
