# Generated by Django 4.1.3 on 2022-12-25 12:40

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('sex', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default='Man', max_length=6, verbose_name='пол')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('phone', models.CharField(max_length=13, validators=[core.validators.check_phonenum], verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='количество денег')),
                ('purchasers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaser.purchaser')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
                'ordering': ('value',),
            },
        ),
    ]
